export const DEFAULT_ELVES = [
  {
    name: "Jingle",
    gender: "boy",
    avatarEmoji: "🧝‍♂️",
    avatarColor: "#b91c1c",
    bio: "Jingle is the fastest sledder in the North Pole and never misses a chance to make you laugh.",
    personality: "Funny, energetic, playful",
    hobbies: "Sledding, snowball fights, telling jokes",
    christmasJob: "Test-drives brand new toys",
    favoriteTreats: "Peppermint cocoa and gumdrops",
    funFacts: "Once raced a reindeer and almost won!",
    greetingStyle: "Hey there, superstar!",
    sortOrder: 1,
  },
  {
    name: "Holly",
    gender: "girl",
    avatarEmoji: "🧝‍♀️",
    avatarColor: "#166534",
    bio: "Holly bakes the fluffiest cookies and always has a warm hug ready for friends.",
    personality: "Sweet, caring, gentle",
    hobbies: "Baking cookies, decorating trees, reading stories",
    christmasJob: "Feeds and brushes the reindeer",
    favoriteTreats: "Sugar cookies with sprinkles",
    funFacts: "Can braid ribbon into the prettiest bows.",
    greetingStyle: "Hello, my dear friend!",
    sortOrder: 2,
  },
  {
    name: "Spark",
    gender: "boy",
    avatarEmoji: "✨",
    avatarColor: "#ca8a04",
    bio: "Spark lights up the workshop with twinkly ideas and bright inventions.",
    personality: "Curious, inventive, cheerful",
    hobbies: "Building gadgets, stargazing, magic tricks",
    christmasJob: "Keeps the Christmas lights twinkling",
    favoriteTreats: "Caramel popcorn stars",
    funFacts: "Invented a snowflake that never melts.",
    greetingStyle: "Sparkle greetings!",
    sortOrder: 3,
  },
  {
    name: "Noel",
    gender: "girl",
    avatarEmoji: "🎄",
    avatarColor: "#15803d",
    bio: "Noel loves quiet snowy evenings and writing the coziest Christmas poems.",
    personality: "Calm, thoughtful, kind",
    hobbies: "Poetry, origami, ice skating",
    christmasJob: "Writes gift tags in golden ink",
    favoriteTreats: "Hot cinnamon tea and shortbread",
    funFacts: "Can fold a paper snowflake in under 10 seconds.",
    greetingStyle: "Warm winter wishes!",
    sortOrder: 4,
  },
  {
    name: "Buddy",
    gender: "boy",
    avatarEmoji: "🎁",
    avatarColor: "#dc2626",
    bio: "Buddy is Santa's helper for wrapping presents with the wildest bows.",
    personality: "Loyal, silly, brave",
    hobbies: "Wrapping gifts, hide-and-seek, drumming",
    christmasJob: "Chief present wrapper",
    favoriteTreats: "Chocolate oranges",
    funFacts: "Knows 42 different bow styles.",
    greetingStyle: "Buddy here, ready for adventure!",
    sortOrder: 5,
  },
  {
    name: "Pepper",
    gender: "girl",
    avatarEmoji: "🍬",
    avatarColor: "#be123c",
    bio: "Pepper runs the candy cane kitchen and loves sharing sweet surprises.",
    personality: "Spunky, generous, witty",
    hobbies: "Candy making, dancing, painting",
    christmasJob: "Stirs the candy cane cauldron",
    favoriteTreats: "Rainbow lollipops",
    funFacts: "Her mittens are always striped.",
    greetingStyle: "Pepper-mint hellos!",
    sortOrder: 6,
  },
  {
    name: "Frost",
    gender: "boy",
    avatarEmoji: "❄️",
    avatarColor: "#0e7490",
    bio: "Frost designs ice sculptures that sparkle under the northern lights.",
    personality: "Cool, creative, patient",
    hobbies: "Ice sculpting, hockey, storytelling",
    christmasJob: "Carves ice lanterns for the village",
    favoriteTreats: "Blueberry snow cones",
    funFacts: "Can whistle like the winter wind.",
    greetingStyle: "Chilly high-five!",
    sortOrder: 7,
  },
  {
    name: "Belle",
    gender: "girl",
    avatarEmoji: "🔔",
    avatarColor: "#a16207",
    bio: "Belle rings the workshop bells and sings carols that make everyone smile.",
    personality: "Musical, joyful, encouraging",
    hobbies: "Singing, bell ringing, knitting scarves",
    christmasJob: "Choir leader of Santa's workshop",
    favoriteTreats: "Honey toast and cocoa",
    funFacts: "Her favorite note is a happy jingle.",
    greetingStyle: "Ring-a-ling hello!",
    sortOrder: 8,
  },
  {
    name: "Dash",
    gender: "boy",
    avatarEmoji: "🦌",
    avatarColor: "#9a3412",
    bio: "Dash trains with the reindeer team and dreams of flying someday.",
    personality: "Adventurous, determined, funny",
    hobbies: "Running, map drawing, cloud watching",
    christmasJob: "Reindeer flight assistant",
    favoriteTreats: "Carrot cupcakes",
    funFacts: "Can name every reindeer by their laugh.",
    greetingStyle: "Ready, set, hello!",
    sortOrder: 9,
  },
  {
    name: "Tinsel",
    gender: "girl",
    avatarEmoji: "🌟",
    avatarColor: "#7c3aed",
    bio: "Tinsel sparkles from head to toe and decorates everything in sight.",
    personality: "Glamorous, friendly, imaginative",
    hobbies: "Decorating, fashion design, glitter crafts",
    christmasJob: "Workshop interior designer",
    favoriteTreats: "Sparkle sugar cookies",
    funFacts: "Leaves a trail of glitter wherever she goes (on purpose).",
    greetingStyle: "Shimmering hello, friend!",
    sortOrder: 10,
  },
  {
    name: "Chip",
    gender: "boy",
    avatarEmoji: "🍪",
    avatarColor: "#92400e",
    bio: "Chip is the cookie quality tester — the most important job, if you ask him.",
    personality: "Goofy, warm-hearted, hungry",
    hobbies: "Cookie tasting, board games, juggling marshmallows",
    christmasJob: "Official cookie quality tester",
    favoriteTreats: "Literally every cookie",
    funFacts: "Has a secret cookie ranking chart.",
    greetingStyle: "Chip-chip hooray!",
    sortOrder: 11,
  },
  {
    name: "Ivy",
    gender: "girl",
    avatarEmoji: "🌿",
    avatarColor: "#14532d",
    bio: "Ivy grows magical holly bushes and teaches plants to twinkle at night.",
    personality: "Gentle, wise, nature-loving",
    hobbies: "Gardening, bird watching, making wreaths",
    christmasJob: "North Pole greenhouse keeper",
    favoriteTreats: "Mint leaves and berry tarts",
    funFacts: "Talks to pine trees (and they answer).",
    greetingStyle: "Leafy love from Ivy!",
    sortOrder: 12,
  },
  {
    name: "Ginger",
    gender: "boy",
    avatarEmoji: "🏠",
    avatarColor: "#c2410c",
    bio: "Ginger builds gingerbread houses so fancy they need tiny streetlights.",
    personality: "Creative, patient, proud",
    hobbies: "Architecture, frosting art, snow forts",
    christmasJob: "Master gingerbread architect",
    favoriteTreats: "Gingerbread men with gumdrop buttons",
    funFacts: "Built a gingerbread castle with a drawbridge.",
    greetingStyle: "Welcome to the sweet side!",
    sortOrder: 13,
  },
  {
    name: "Merry",
    gender: "girl",
    avatarEmoji: "🎀",
    avatarColor: "#e11d48",
    bio: "Merry spreads cheer faster than falling snow and remembers every friend's birthday.",
    personality: "Bubbly, thoughtful, optimistic",
    hobbies: "Party planning, scrapbooking, dancing",
    christmasJob: "Chief cheer spreader",
    favoriteTreats: "Candy cane milkshakes",
    funFacts: "Sends thank-you notes to the stars.",
    greetingStyle: "Merry greetings, super friend!",
    sortOrder: 14,
  },
  {
    name: "Rudy",
    gender: "boy",
    avatarEmoji: "🔴",
    avatarColor: "#b91c1c",
    bio: "Rudy lights the night path with his glowing ideas and big heart.",
    personality: "Brave, helpful, modest",
    hobbies: "Night walks, puzzle solving, kite flying",
    christmasJob: "Path lighter for Christmas Eve",
    favoriteTreats: "Cherry snowballs",
    funFacts: "His nose only glows when he giggles.",
    greetingStyle: "Glow-powered hello!",
    sortOrder: 15,
  },
  {
    name: "Snowflake",
    gender: "girl",
    avatarEmoji: " freeze",
    avatarColor: "#0369a1",
    bio: "Snowflake studies every unique flake and paints them into storybooks.",
    personality: "Dreamy, artistic, soft-spoken",
    hobbies: "Painting, collecting crystals, quiet reading",
    christmasJob: "Snowflake archivist",
    favoriteTreats: "Vanilla snow cream",
    funFacts: "Has never seen two identical snowflakes.",
    greetingStyle: "Soft snowy hello...",
    sortOrder: 16,
  },
  {
    name: "Bells",
    gender: "boy",
    avatarEmoji: "🎶",
    avatarColor: "#4d7c0f",
    bio: "Bells composes catchy jingles that get stuck in Santa's head all year.",
    personality: "Musical, upbeat, clever",
    hobbies: "Composing, whistling, drum circles",
    christmasJob: "Workshop jingle composer",
    favoriteTreats: "Toffee notes and cocoa",
    funFacts: "Can play sleigh bells with his toes.",
    greetingStyle: "Hit it — hello!",
    sortOrder: 17,
  },
  {
    name: "Cinnamon",
    gender: "girl",
    avatarEmoji: "🧁",
    avatarColor: "#9f1239",
    bio: "Cinnamon fills the air with cozy scents and the kindest compliments.",
    personality: "Cozy, affirming, humorous",
    hobbies: "Baking pies, storytelling, knitting",
    christmasJob: "Scent master of the bakery",
    favoriteTreats: "Cinnamon rolls taller than her hat",
    funFacts: "Her scarf smells like Christmas morning.",
    greetingStyle: "Cozy cinnamon hugs!",
    sortOrder: 18,
  },
  {
    name: "Twig",
    gender: "boy",
    avatarEmoji: "🪵",
    avatarColor: "#365314",
    bio: "Twig crafts tiny wooden toys and leaves secret kindness notes in coat pockets.",
    personality: "Quiet, crafty, generous",
    hobbies: "Wood carving, birdhouses, treasure maps",
    christmasJob: "Wooden toy carver",
    favoriteTreats: "Maple cookies",
    funFacts: "Carved a reindeer smaller than a thimble.",
    greetingStyle: "Hey friend, from the workshop bench!",
    sortOrder: 19,
  },
  {
    name: "Lumina",
    gender: "girl",
    avatarEmoji: "🕯️",
    avatarColor: "#f59e0b",
    bio: "Lumina keeps the lanterns glowing so no friend ever feels left in the dark.",
    personality: "Hopeful, wise, protective",
    hobbies: "Lantern making, night sky stories, mentoring little elves",
    christmasJob: "Keeper of the northern lanterns",
    favoriteTreats: "Honey cakes and warm milk",
    funFacts: "Her lantern never goes out on Christmas Eve.",
    greetingStyle: "May your path glow brightly!",
    sortOrder: 20,
  },
];
export const DEFAULT_QUOTES = [
  { text: "Kindness is Christmas magic.", author: "Santa" },
  { text: "Believe in the impossible.", author: "The Elves" },
  { text: "Every act of kindness helps Santa.", author: "Mrs. Claus" },
  { text: "The best gift is a warm heart.", author: "Holly" },
  { text: "Snowflakes are kisses from the sky.", author: "Snowflake" },
  { text: "Share joy like candy canes — freely!", author: "Pepper" },
  { text: "A smile is the brightest ornament.", author: "Tinsel" },
  { text: "Friends make every season sparkle.", author: "Jingle" },
  { text: "Courage glows brighter than any lantern.", author: "Lumina" },
  { text: "Dream big, wrap bigger.", author: "Buddy" },
  { text: "Magic grows when we help each other.", author: "Noel" },
  { text: "Today is a perfect day for wonder.", author: "Spark" },
];
export const DEFAULT_WALLS = [
  {
    name: "Classic Workshop",
    description: "Deep red and evergreen stripes like Santa's study",
    backgroundCss:
      "linear-gradient(135deg, #450a0a 0%, #14532d 50%, #1c1917 100%)",
    patternType: "gradient",
    primaryColor: "#450a0a",
    secondaryColor: "#14532d",
    accentColor: "#fbbf24",
  },
  {
    name: "Midnight North Pole",
    description: "Dark sky with emerald aurora vibes",
    backgroundCss:
      "radial-gradient(circle at 20% 20%, #166534 0%, transparent 40%), radial-gradient(circle at 80% 0%, #7f1d1d 0%, transparent 35%), linear-gradient(180deg, #020617 0%, #052e16 100%)",
    patternType: "aurora",
    primaryColor: "#020617",
    secondaryColor: "#166534",
    accentColor: "#f87171",
  },
  {
    name: "Candy Cane Lane",
    description: "Playful red and white diagonal candy stripes",
    backgroundCss:
      "repeating-linear-gradient(45deg, #7f1d1d, #7f1d1d 20px, #fef2f2 20px, #fef2f2 40px)",
    patternType: "stripes",
    primaryColor: "#7f1d1d",
    secondaryColor: "#fef2f2",
    accentColor: "#166534",
  },
  {
    name: "Golden Gift Wrap",
    description: "Rich black with gold shimmer panels",
    backgroundCss:
      "linear-gradient(120deg, #0a0a0a 0%, #1c1917 35%, #713f12 70%, #0a0a0a 100%)",
    patternType: "shimmer",
    primaryColor: "#0a0a0a",
    secondaryColor: "#713f12",
    accentColor: "#facc15",
  },
  {
    name: "Evergreen Forest",
    description: "Layered greens like a snowy pine forest",
    backgroundCss:
      "linear-gradient(180deg, #052e16 0%, #14532d 40%, #166534 70%, #022c22 100%)",
    patternType: "forest",
    primaryColor: "#052e16",
    secondaryColor: "#166534",
    accentColor: "#fef3c7",
  },
  {
    name: "Twinkle Lights",
    description: "Dark wall with colorful holiday light dots",
    backgroundCss:
      "radial-gradient(circle at 10% 20%, #fbbf24 0 4px, transparent 5px), radial-gradient(circle at 30% 60%, #ef4444 0 4px, transparent 5px), radial-gradient(circle at 55% 25%, #22c55e 0 4px, transparent 5px), radial-gradient(circle at 75% 70%, #38bdf8 0 4px, transparent 5px), radial-gradient(circle at 90% 40%, #f472b6 0 4px, transparent 5px), linear-gradient(180deg, #111827, #1f2937)",
    patternType: "lights",
    primaryColor: "#111827",
    secondaryColor: "#1f2937",
    accentColor: "#fbbf24",
  },
];
export const DEFAULT_MUSIC = [
  {
    title: "Sleigh Ride Dream",
    artist: "North Pole Orchestra",
    url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
    sortOrder: 1,
  },
  {
    title: "Workshop Whistle",
    artist: "Elven Ensemble",
    url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3",
    sortOrder: 2,
  },
  {
    title: "Snowfall Lullaby",
    artist: "Aurora Choir",
    url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3",
    sortOrder: 3,
  },
];
